FORMAT: 1A

# HAL Model

[HAL Specification](https://tools.ietf.org/html/draft-kelly-json-hal-07): `draft-kelly-json-hal-07`

# List of Orders [/orders]
## Retieve [GET]
- Response 200
    - Attributes (List of Orders)


# Data Structures

## HAL Resource Base (object)

Abstract base object. Not to be used directly. See `HAL Resource`.

## HAL Resource (HAL Resource Base)

HAL Specification: [Resource Object](https://tools.ietf.org/html/draft-kelly-json-hal-07#section-4)

### Properties
- `_links`
    - *relation* (Link)

- `_embedded`
    - *relation* (Embedded)

## Embedded (enum)

HAL Specification:  [`_embedded` property value](https://tools.ietf.org/html/draft-kelly-json-hal-07#section-4.1.2)

The value is either a descendant of `HAL Resource Base` or an array of its descendats.

### Members
- (HAL Resource Base)
- (array[HAL Resource Base])

## Link (object)

HAL Specification: [Link Object](https://tools.ietf.org/html/draft-kelly-json-hal-07#section-5)

### Properties
- href (required)
- templated (boolean)
- type
- deprecation
- name
- profile
- title
- hreflang


## List of Orders (HAL Resource)

HAL Specification: [Example Document](https://tools.ietf.org/html/draft-kelly-json-hal-07#section-6)

### Properties
- `_links`
    - self (Link)
    - next (Link)
    - find (Link)

- `_embedded`
    - orders (array[Order])

- currentlyProcessing: 14 (number)
- shippedToday: 20 (number)


## Order (HAL Resource)
- `_links`
    - self (Link)
    - basket (Link)
    - customer (Link)

- total (number)
    - Sample: 30
    - Sample: 20

- currency: USD (string)

- status (enum)
    - processing
    - shipped